"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const router = (0, express_1.Router)();
router.post('/signup', auth_controller_1.registerUser);
router.post('/login', auth_controller_1.loginUser);
router.post('/firebase-login', auth_controller_1.firebaseLogin);
router.get('/check/username/:username', auth_controller_1.checkUsername);
router.get('/check/email/:email', auth_controller_1.checkEmail);
router.get('/check/availability', auth_controller_1.checkAvailability);
exports.default = router;
